// Generated by gencpp from file rc_msgs/serial.msg
// DO NOT EDIT!


#ifndef RC_MSGS_MESSAGE_SERIAL_H
#define RC_MSGS_MESSAGE_SERIAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rc_msgs
{
template <class ContainerAllocator>
struct serial_
{
  typedef serial_<ContainerAllocator> Type;

  serial_()
    : stamp()
    , data()  {
    }
  serial_(const ContainerAllocator& _alloc)
    : stamp()
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rc_msgs::serial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rc_msgs::serial_<ContainerAllocator> const> ConstPtr;

}; // struct serial_

typedef ::rc_msgs::serial_<std::allocator<void> > serial;

typedef boost::shared_ptr< ::rc_msgs::serial > serialPtr;
typedef boost::shared_ptr< ::rc_msgs::serial const> serialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rc_msgs::serial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rc_msgs::serial_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rc_msgs::serial_<ContainerAllocator1> & lhs, const ::rc_msgs::serial_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rc_msgs::serial_<ContainerAllocator1> & lhs, const ::rc_msgs::serial_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rc_msgs::serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_msgs::serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_msgs::serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_msgs::serial_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_msgs::serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_msgs::serial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rc_msgs::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c2996107ba4a77d3150497cc03c74e2";
  }

  static const char* value(const ::rc_msgs::serial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c2996107ba4a77dULL;
  static const uint64_t static_value2 = 0x3150497cc03c74e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rc_msgs::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rc_msgs/serial";
  }

  static const char* value(const ::rc_msgs::serial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rc_msgs::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 包含时间戳\n"
"time stamp\n"
"\n"
"# 包含float类型的数组\n"
"float32[] data\n"
;
  }

  static const char* value(const ::rc_msgs::serial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rc_msgs::serial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rc_msgs::serial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rc_msgs::serial_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RC_MSGS_MESSAGE_SERIAL_H
