// Generated by gencpp from file rc_msgs/yolo_detectorArray.msg
// DO NOT EDIT!


#ifndef RC_MSGS_MESSAGE_YOLO_DETECTORARRAY_H
#define RC_MSGS_MESSAGE_YOLO_DETECTORARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rc_msgs/yolo_detector.h>

namespace rc_msgs
{
template <class ContainerAllocator>
struct yolo_detectorArray_
{
  typedef yolo_detectorArray_<ContainerAllocator> Type;

  yolo_detectorArray_()
    : header()
    , boxes()  {
    }
  yolo_detectorArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , boxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rc_msgs::yolo_detector_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::rc_msgs::yolo_detector_<ContainerAllocator> >> _boxes_type;
  _boxes_type boxes;





  typedef boost::shared_ptr< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> const> ConstPtr;

}; // struct yolo_detectorArray_

typedef ::rc_msgs::yolo_detectorArray_<std::allocator<void> > yolo_detectorArray;

typedef boost::shared_ptr< ::rc_msgs::yolo_detectorArray > yolo_detectorArrayPtr;
typedef boost::shared_ptr< ::rc_msgs::yolo_detectorArray const> yolo_detectorArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rc_msgs::yolo_detectorArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rc_msgs::yolo_detectorArray_<ContainerAllocator1> & lhs, const ::rc_msgs::yolo_detectorArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.boxes == rhs.boxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rc_msgs::yolo_detectorArray_<ContainerAllocator1> & lhs, const ::rc_msgs::yolo_detectorArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "276533dc1a5df7655d0543cac92ab85f";
  }

  static const char* value(const ::rc_msgs::yolo_detectorArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x276533dc1a5df765ULL;
  static const uint64_t static_value2 = 0x5d0543cac92ab85fULL;
};

template<class ContainerAllocator>
struct DataType< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rc_msgs/yolo_detectorArray";
  }

  static const char* value(const ::rc_msgs::yolo_detectorArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 带类别信息的2D边界框数组消息\n"
"std_msgs/Header header        # 消息头部，包含时间戳和坐标系\n"
"yolo_detector[] boxes       # 边界框数组\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rc_msgs/yolo_detector\n"
"# 描述单个2D边界框的消息\n"
"geometry_msgs/Pose2D center  # 边界框中心坐标 (x, y)，单位通常为像素或米（取决于坐标系）\n"
"float32 size_x                # x方向尺寸（宽度）\n"
"float32 size_y                # y方向尺寸（高度）\n"
"int32 cls #目标类别\n"
"\n"
"   \n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::rc_msgs::yolo_detectorArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yolo_detectorArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rc_msgs::yolo_detectorArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rc_msgs::yolo_detectorArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "boxes: ";
    if (v.boxes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.boxes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::rc_msgs::yolo_detector_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.boxes[i]);
    }
    if (v.boxes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // RC_MSGS_MESSAGE_YOLO_DETECTORARRAY_H
