// Generated by gencpp from file rc_msgs/yolo_detector.msg
// DO NOT EDIT!


#ifndef RC_MSGS_MESSAGE_YOLO_DETECTOR_H
#define RC_MSGS_MESSAGE_YOLO_DETECTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace rc_msgs
{
template <class ContainerAllocator>
struct yolo_detector_
{
  typedef yolo_detector_<ContainerAllocator> Type;

  yolo_detector_()
    : center()
    , size_x(0.0)
    , size_y(0.0)
    , cls(0)  {
    }
  yolo_detector_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , size_x(0.0)
    , size_y(0.0)
    , cls(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef float _size_x_type;
  _size_x_type size_x;

   typedef float _size_y_type;
  _size_y_type size_y;

   typedef int32_t _cls_type;
  _cls_type cls;





  typedef boost::shared_ptr< ::rc_msgs::yolo_detector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rc_msgs::yolo_detector_<ContainerAllocator> const> ConstPtr;

}; // struct yolo_detector_

typedef ::rc_msgs::yolo_detector_<std::allocator<void> > yolo_detector;

typedef boost::shared_ptr< ::rc_msgs::yolo_detector > yolo_detectorPtr;
typedef boost::shared_ptr< ::rc_msgs::yolo_detector const> yolo_detectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rc_msgs::yolo_detector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rc_msgs::yolo_detector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rc_msgs::yolo_detector_<ContainerAllocator1> & lhs, const ::rc_msgs::yolo_detector_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.size_x == rhs.size_x &&
    lhs.size_y == rhs.size_y &&
    lhs.cls == rhs.cls;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rc_msgs::yolo_detector_<ContainerAllocator1> & lhs, const ::rc_msgs::yolo_detector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rc_msgs::yolo_detector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rc_msgs::yolo_detector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_msgs::yolo_detector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rc_msgs::yolo_detector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_msgs::yolo_detector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rc_msgs::yolo_detector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rc_msgs::yolo_detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb27bdcd0f972d1bdf70000491495017";
  }

  static const char* value(const ::rc_msgs::yolo_detector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb27bdcd0f972d1bULL;
  static const uint64_t static_value2 = 0xdf70000491495017ULL;
};

template<class ContainerAllocator>
struct DataType< ::rc_msgs::yolo_detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rc_msgs/yolo_detector";
  }

  static const char* value(const ::rc_msgs::yolo_detector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rc_msgs::yolo_detector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 描述单个2D边界框的消息\n"
"geometry_msgs/Pose2D center  # 边界框中心坐标 (x, y)，单位通常为像素或米（取决于坐标系）\n"
"float32 size_x                # x方向尺寸（宽度）\n"
"float32 size_y                # y方向尺寸（高度）\n"
"int32 cls #目标类别\n"
"\n"
"   \n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::rc_msgs::yolo_detector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rc_msgs::yolo_detector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.size_x);
      stream.next(m.size_y);
      stream.next(m.cls);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yolo_detector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rc_msgs::yolo_detector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rc_msgs::yolo_detector_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "center: ";
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size_x: ";
    Printer<float>::stream(s, indent + "  ", v.size_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "size_y: ";
    Printer<float>::stream(s, indent + "  ", v.size_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cls: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cls);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RC_MSGS_MESSAGE_YOLO_DETECTOR_H
